version: '3.5'
services:
  tidder-eureka:
    container_name: tidder-eureka
    build: ./tidder-eureka/
    restart: always
    ports:
      - "8761:8761"
  tidder-zuul:
    container_name: tidder-zuul
    build: ./tidder-zuul/
    restart: always
    depends_on:
      - tidder-eureka
      - tidder-front
    ports:
      - "8080:8080"
  tidder-front:
    build: ./tidder-front/
    restart: always
    depends_on:
      - tidder-eureka
    ports:
      - "9090"
    deploy:
      mode: replicated
      replicas: 6
  tidder-oauth:
    build: ./tidder-oauth/
    restart: always
    depends_on:
      - tidder-eureka
    ports:
      - "9099"
    deploy:
      mode: replicated
      replicas: 6
  tidder-test1:
    build: ./tidder-test1/
    restart: always
    depends_on:
      - tidder-eureka
    ports:
      - "9092" 
    deploy:
      mode: replicated 
      replicas: 6
  tidder-test2:
    build: ./tidder-test2/
    restart: always
    depends_on:
      - tidder-eureka
    ports:
      - "9091" 
    deploy:
      mode: replicated
      replicas: 6
