version: '3.5'
services:
  db:
    container_name: tidder-mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: tidder
      MYSQL_USER: tidderadmin
      MYSQL_PASSWORD: nimdareddit
    ports:
    - "3306:3306"
  tidder-eureka:
    container_name: tidder-eureka
    build: ./tidder-eureka/
    restart: always
    ports:
    - "8761:8761"
  tidder-zuul:
    container_name: tidder-zuul
    build: ./tidder-zuul/
    restart: always
    depends_on:
      - tidder-eureka
      - tidder-front
    ports:
    - "8080:8080"
  tidder-front:
    build: ./tidder-front/
    restart: always
    depends_on:
    - tidder-eureka
    - db
    ports:
    - "9090"
    deploy:
      mode: replicated
      replicas: 1
  tidder-oauth:
    build: ./tidder-oauth/
    restart: always
    depends_on:
    - tidder-eureka
    - db
    ports:
    - "9099"
    deploy:
      mode: replicated
      replicas: 1
  tidder-test1:
    build: ./tidder-test1/
    restart: always
    depends_on:
    - tidder-eureka
    ports:
    - "9092"
    deploy:
      mode: replicated 
      replicas: 1
  tidder-test2:
    build: ./tidder-test2/
    restart: always
    depends_on:
    - tidder-eureka
    ports:
    - "9091"
    deploy:
      mode: replicated
      replicas: 1
  tidder-user:
    build: ./tidder-user/
    restart: always
    depends_on:
      - tidder-eureka
    ports:
      - "9090"
    deploy:
      mode: replicated
      replicas: 5
networks:
  tidder_default:
    ipam:
      driver: default
      config:
      - subnet: 46.4.245.160/28
