version: '3.5'
services:
  db:
    container_name: tidder-mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: tidder
      MYSQL_USER: tidderadmin
      MYSQL_PASSWORD: nimdareddit
    ports:
    - "3306:3306"
  tidder-eureka:
    container_name: tidder-eureka
    build: ./tidder-eureka/
    restart: always
    ports:
    - "8761:8761"
  tidder-zuul:
    container_name: tidder-zuul
    build: ./tidder-zuul/
    restart: always
    depends_on:
      - tidder-eureka
      - tidder-front
    ports:
    - "8080:8080"
  tidder-front:
    build: ./tidder-front/
    restart: always
    depends_on:
    - tidder-eureka
    - db
    ports:
    - "9090"
    deploy:
      mode: replicated
      replicas: 1
  tidder-user:
    build: ./tidder-user/
    restart: always
    depends_on:
      - tidder-eureka
    ports:
      - "9090"
    deploy:
      mode: replicated
      replicas: 1
  tidder-topic:
    build: ./tidder-topic/
    restart: always
    depends_on:
      - tidder-eureka
    ports:
      - "9090"
    deploy:
      mode: replicated
      replicas: 1
  tidder-post:
    build: ./tidder-post/
    restart: always
    depends_on:
      - tidder-eureka
    ports:
      - "9090"
    deploy:
      mode: replicated
      replicas: 1
  tidder-likes:
    build: ./tidder-likes/
    restart: always
    depends_on:
      - tidder-eureka
    ports:
      - "9090"
    deploy:
      mode: replicated
      replicas: 1
